# CMAKE generated file: DO NOT EDIT!
# Generated by "MinGW Makefiles" Generator, CMake Version 4.2

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

SHELL = cmd.exe

# The CMake executable.
CMAKE_COMMAND = "C:\Program Files\CMake\bin\cmake.exe"

# The command to remove a file.
RM = "C:\Program Files\CMake\bin\cmake.exe" -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = C:\Users\rkuru\ray_tracer

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = C:\Users\rkuru\ray_tracer

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	"C:\Program Files\CMake\bin\cmake-gui.exe" -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	"C:\Program Files\CMake\bin\cmake.exe" --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	"C:\Program Files\CMake\bin\cmake.exe" -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	"C:\Program Files\CMake\bin\cmake.exe" -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	"C:\Program Files\CMake\bin\cmake.exe" -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	"C:\Program Files\CMake\bin\cmake.exe" -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	"C:\Program Files\CMake\bin\cmake.exe" -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	"C:\Program Files\CMake\bin\cmake.exe" -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start C:\Users\rkuru\ray_tracer\CMakeFiles C:\Users\rkuru\ray_tracer\\CMakeFiles\progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start C:\Users\rkuru\ray_tracer\CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named OpenGLProject

# Build rule for target.
OpenGLProject: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 OpenGLProject
.PHONY : OpenGLProject

# fast build rule for target.
OpenGLProject/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\OpenGLProject.dir\build.make CMakeFiles/OpenGLProject.dir/build
.PHONY : OpenGLProject/fast

#=============================================================================
# Target rules for targets named uninstall

# Build rule for target.
uninstall: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 uninstall
.PHONY : uninstall

# fast build rule for target.
uninstall/fast:
	$(MAKE) $(MAKESILENT) -f thirdparty\glfw-3.3.2\CMakeFiles\uninstall.dir\build.make thirdparty/glfw-3.3.2/CMakeFiles/uninstall.dir/build
.PHONY : uninstall/fast

#=============================================================================
# Target rules for targets named glfw

# Build rule for target.
glfw: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 glfw
.PHONY : glfw

# fast build rule for target.
glfw/fast:
	$(MAKE) $(MAKESILENT) -f thirdparty\glfw-3.3.2\src\CMakeFiles\glfw.dir\build.make thirdparty/glfw-3.3.2/src/CMakeFiles/glfw.dir/build
.PHONY : glfw/fast

src/main.obj: src/main.cpp.obj
.PHONY : src/main.obj

# target to build an object file
src/main.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\OpenGLProject.dir\build.make CMakeFiles/OpenGLProject.dir/src/main.cpp.obj
.PHONY : src/main.cpp.obj

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\OpenGLProject.dir\build.make CMakeFiles/OpenGLProject.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\OpenGLProject.dir\build.make CMakeFiles/OpenGLProject.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

thirdparty/imgui-docking/imgui.obj: thirdparty/imgui-docking/imgui.cpp.obj
.PHONY : thirdparty/imgui-docking/imgui.obj

# target to build an object file
thirdparty/imgui-docking/imgui.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\OpenGLProject.dir\build.make CMakeFiles/OpenGLProject.dir/thirdparty/imgui-docking/imgui.cpp.obj
.PHONY : thirdparty/imgui-docking/imgui.cpp.obj

thirdparty/imgui-docking/imgui.i: thirdparty/imgui-docking/imgui.cpp.i
.PHONY : thirdparty/imgui-docking/imgui.i

# target to preprocess a source file
thirdparty/imgui-docking/imgui.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\OpenGLProject.dir\build.make CMakeFiles/OpenGLProject.dir/thirdparty/imgui-docking/imgui.cpp.i
.PHONY : thirdparty/imgui-docking/imgui.cpp.i

thirdparty/imgui-docking/imgui.s: thirdparty/imgui-docking/imgui.cpp.s
.PHONY : thirdparty/imgui-docking/imgui.s

# target to generate assembly for a file
thirdparty/imgui-docking/imgui.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\OpenGLProject.dir\build.make CMakeFiles/OpenGLProject.dir/thirdparty/imgui-docking/imgui.cpp.s
.PHONY : thirdparty/imgui-docking/imgui.cpp.s

thirdparty/imgui-docking/imgui_demo.obj: thirdparty/imgui-docking/imgui_demo.cpp.obj
.PHONY : thirdparty/imgui-docking/imgui_demo.obj

# target to build an object file
thirdparty/imgui-docking/imgui_demo.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\OpenGLProject.dir\build.make CMakeFiles/OpenGLProject.dir/thirdparty/imgui-docking/imgui_demo.cpp.obj
.PHONY : thirdparty/imgui-docking/imgui_demo.cpp.obj

thirdparty/imgui-docking/imgui_demo.i: thirdparty/imgui-docking/imgui_demo.cpp.i
.PHONY : thirdparty/imgui-docking/imgui_demo.i

# target to preprocess a source file
thirdparty/imgui-docking/imgui_demo.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\OpenGLProject.dir\build.make CMakeFiles/OpenGLProject.dir/thirdparty/imgui-docking/imgui_demo.cpp.i
.PHONY : thirdparty/imgui-docking/imgui_demo.cpp.i

thirdparty/imgui-docking/imgui_demo.s: thirdparty/imgui-docking/imgui_demo.cpp.s
.PHONY : thirdparty/imgui-docking/imgui_demo.s

# target to generate assembly for a file
thirdparty/imgui-docking/imgui_demo.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\OpenGLProject.dir\build.make CMakeFiles/OpenGLProject.dir/thirdparty/imgui-docking/imgui_demo.cpp.s
.PHONY : thirdparty/imgui-docking/imgui_demo.cpp.s

thirdparty/imgui-docking/imgui_draw.obj: thirdparty/imgui-docking/imgui_draw.cpp.obj
.PHONY : thirdparty/imgui-docking/imgui_draw.obj

# target to build an object file
thirdparty/imgui-docking/imgui_draw.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\OpenGLProject.dir\build.make CMakeFiles/OpenGLProject.dir/thirdparty/imgui-docking/imgui_draw.cpp.obj
.PHONY : thirdparty/imgui-docking/imgui_draw.cpp.obj

thirdparty/imgui-docking/imgui_draw.i: thirdparty/imgui-docking/imgui_draw.cpp.i
.PHONY : thirdparty/imgui-docking/imgui_draw.i

# target to preprocess a source file
thirdparty/imgui-docking/imgui_draw.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\OpenGLProject.dir\build.make CMakeFiles/OpenGLProject.dir/thirdparty/imgui-docking/imgui_draw.cpp.i
.PHONY : thirdparty/imgui-docking/imgui_draw.cpp.i

thirdparty/imgui-docking/imgui_draw.s: thirdparty/imgui-docking/imgui_draw.cpp.s
.PHONY : thirdparty/imgui-docking/imgui_draw.s

# target to generate assembly for a file
thirdparty/imgui-docking/imgui_draw.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\OpenGLProject.dir\build.make CMakeFiles/OpenGLProject.dir/thirdparty/imgui-docking/imgui_draw.cpp.s
.PHONY : thirdparty/imgui-docking/imgui_draw.cpp.s

thirdparty/imgui-docking/imgui_impl_glfw.obj: thirdparty/imgui-docking/imgui_impl_glfw.cpp.obj
.PHONY : thirdparty/imgui-docking/imgui_impl_glfw.obj

# target to build an object file
thirdparty/imgui-docking/imgui_impl_glfw.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\OpenGLProject.dir\build.make CMakeFiles/OpenGLProject.dir/thirdparty/imgui-docking/imgui_impl_glfw.cpp.obj
.PHONY : thirdparty/imgui-docking/imgui_impl_glfw.cpp.obj

thirdparty/imgui-docking/imgui_impl_glfw.i: thirdparty/imgui-docking/imgui_impl_glfw.cpp.i
.PHONY : thirdparty/imgui-docking/imgui_impl_glfw.i

# target to preprocess a source file
thirdparty/imgui-docking/imgui_impl_glfw.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\OpenGLProject.dir\build.make CMakeFiles/OpenGLProject.dir/thirdparty/imgui-docking/imgui_impl_glfw.cpp.i
.PHONY : thirdparty/imgui-docking/imgui_impl_glfw.cpp.i

thirdparty/imgui-docking/imgui_impl_glfw.s: thirdparty/imgui-docking/imgui_impl_glfw.cpp.s
.PHONY : thirdparty/imgui-docking/imgui_impl_glfw.s

# target to generate assembly for a file
thirdparty/imgui-docking/imgui_impl_glfw.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\OpenGLProject.dir\build.make CMakeFiles/OpenGLProject.dir/thirdparty/imgui-docking/imgui_impl_glfw.cpp.s
.PHONY : thirdparty/imgui-docking/imgui_impl_glfw.cpp.s

thirdparty/imgui-docking/imgui_impl_opengl3.obj: thirdparty/imgui-docking/imgui_impl_opengl3.cpp.obj
.PHONY : thirdparty/imgui-docking/imgui_impl_opengl3.obj

# target to build an object file
thirdparty/imgui-docking/imgui_impl_opengl3.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\OpenGLProject.dir\build.make CMakeFiles/OpenGLProject.dir/thirdparty/imgui-docking/imgui_impl_opengl3.cpp.obj
.PHONY : thirdparty/imgui-docking/imgui_impl_opengl3.cpp.obj

thirdparty/imgui-docking/imgui_impl_opengl3.i: thirdparty/imgui-docking/imgui_impl_opengl3.cpp.i
.PHONY : thirdparty/imgui-docking/imgui_impl_opengl3.i

# target to preprocess a source file
thirdparty/imgui-docking/imgui_impl_opengl3.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\OpenGLProject.dir\build.make CMakeFiles/OpenGLProject.dir/thirdparty/imgui-docking/imgui_impl_opengl3.cpp.i
.PHONY : thirdparty/imgui-docking/imgui_impl_opengl3.cpp.i

thirdparty/imgui-docking/imgui_impl_opengl3.s: thirdparty/imgui-docking/imgui_impl_opengl3.cpp.s
.PHONY : thirdparty/imgui-docking/imgui_impl_opengl3.s

# target to generate assembly for a file
thirdparty/imgui-docking/imgui_impl_opengl3.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\OpenGLProject.dir\build.make CMakeFiles/OpenGLProject.dir/thirdparty/imgui-docking/imgui_impl_opengl3.cpp.s
.PHONY : thirdparty/imgui-docking/imgui_impl_opengl3.cpp.s

thirdparty/imgui-docking/imgui_tables.obj: thirdparty/imgui-docking/imgui_tables.cpp.obj
.PHONY : thirdparty/imgui-docking/imgui_tables.obj

# target to build an object file
thirdparty/imgui-docking/imgui_tables.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\OpenGLProject.dir\build.make CMakeFiles/OpenGLProject.dir/thirdparty/imgui-docking/imgui_tables.cpp.obj
.PHONY : thirdparty/imgui-docking/imgui_tables.cpp.obj

thirdparty/imgui-docking/imgui_tables.i: thirdparty/imgui-docking/imgui_tables.cpp.i
.PHONY : thirdparty/imgui-docking/imgui_tables.i

# target to preprocess a source file
thirdparty/imgui-docking/imgui_tables.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\OpenGLProject.dir\build.make CMakeFiles/OpenGLProject.dir/thirdparty/imgui-docking/imgui_tables.cpp.i
.PHONY : thirdparty/imgui-docking/imgui_tables.cpp.i

thirdparty/imgui-docking/imgui_tables.s: thirdparty/imgui-docking/imgui_tables.cpp.s
.PHONY : thirdparty/imgui-docking/imgui_tables.s

# target to generate assembly for a file
thirdparty/imgui-docking/imgui_tables.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\OpenGLProject.dir\build.make CMakeFiles/OpenGLProject.dir/thirdparty/imgui-docking/imgui_tables.cpp.s
.PHONY : thirdparty/imgui-docking/imgui_tables.cpp.s

thirdparty/imgui-docking/imgui_widgets.obj: thirdparty/imgui-docking/imgui_widgets.cpp.obj
.PHONY : thirdparty/imgui-docking/imgui_widgets.obj

# target to build an object file
thirdparty/imgui-docking/imgui_widgets.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\OpenGLProject.dir\build.make CMakeFiles/OpenGLProject.dir/thirdparty/imgui-docking/imgui_widgets.cpp.obj
.PHONY : thirdparty/imgui-docking/imgui_widgets.cpp.obj

thirdparty/imgui-docking/imgui_widgets.i: thirdparty/imgui-docking/imgui_widgets.cpp.i
.PHONY : thirdparty/imgui-docking/imgui_widgets.i

# target to preprocess a source file
thirdparty/imgui-docking/imgui_widgets.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\OpenGLProject.dir\build.make CMakeFiles/OpenGLProject.dir/thirdparty/imgui-docking/imgui_widgets.cpp.i
.PHONY : thirdparty/imgui-docking/imgui_widgets.cpp.i

thirdparty/imgui-docking/imgui_widgets.s: thirdparty/imgui-docking/imgui_widgets.cpp.s
.PHONY : thirdparty/imgui-docking/imgui_widgets.s

# target to generate assembly for a file
thirdparty/imgui-docking/imgui_widgets.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\OpenGLProject.dir\build.make CMakeFiles/OpenGLProject.dir/thirdparty/imgui-docking/imgui_widgets.cpp.s
.PHONY : thirdparty/imgui-docking/imgui_widgets.cpp.s

# Help Target
help:
	@echo The following are some of the valid targets for this Makefile:
	@echo ... all (the default if no target is provided)
	@echo ... clean
	@echo ... depend
	@echo ... edit_cache
	@echo ... install
	@echo ... install/local
	@echo ... install/strip
	@echo ... list_install_components
	@echo ... rebuild_cache
	@echo ... uninstall
	@echo ... OpenGLProject
	@echo ... glfw
	@echo ... src/main.obj
	@echo ... src/main.i
	@echo ... src/main.s
	@echo ... thirdparty/imgui-docking/imgui.obj
	@echo ... thirdparty/imgui-docking/imgui.i
	@echo ... thirdparty/imgui-docking/imgui.s
	@echo ... thirdparty/imgui-docking/imgui_demo.obj
	@echo ... thirdparty/imgui-docking/imgui_demo.i
	@echo ... thirdparty/imgui-docking/imgui_demo.s
	@echo ... thirdparty/imgui-docking/imgui_draw.obj
	@echo ... thirdparty/imgui-docking/imgui_draw.i
	@echo ... thirdparty/imgui-docking/imgui_draw.s
	@echo ... thirdparty/imgui-docking/imgui_impl_glfw.obj
	@echo ... thirdparty/imgui-docking/imgui_impl_glfw.i
	@echo ... thirdparty/imgui-docking/imgui_impl_glfw.s
	@echo ... thirdparty/imgui-docking/imgui_impl_opengl3.obj
	@echo ... thirdparty/imgui-docking/imgui_impl_opengl3.i
	@echo ... thirdparty/imgui-docking/imgui_impl_opengl3.s
	@echo ... thirdparty/imgui-docking/imgui_tables.obj
	@echo ... thirdparty/imgui-docking/imgui_tables.i
	@echo ... thirdparty/imgui-docking/imgui_tables.s
	@echo ... thirdparty/imgui-docking/imgui_widgets.obj
	@echo ... thirdparty/imgui-docking/imgui_widgets.i
	@echo ... thirdparty/imgui-docking/imgui_widgets.s
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 0
.PHONY : cmake_check_build_system

